# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  - group: pipelineNestjs

jobs:
- job: deploy_lambda
  pool: 
    name: Default
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  steps:
 
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js 12'
  - script: npm install yarn
    displayName: 'Install Yarn'
  - script: |
      aws configure set aws_access_key_id $(AWS-ACCESS-KEY-ID)
      aws configure set aws_secret_access_key $(AWS-SECRET-ACCESS-KEY)
      aws configure set region us-east-1
    displayName: 'Configure AWS'
  - script: |
      yarn install
      yarn build
    displayName: 'Build'
  - script: yarn test
    displayName: 'Test'
  - script: yarn sls-deploy
    displayName: 'Deploy'

- job: deploy_ecs
  pool: 
    name: Default
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
